Форма:
 прямоугольник:
    annotation_form: прямоугольник
    barcode_form: ST
 круг:
    annotation_form: круг
    barcode_form: KG
 овал:
    annotation_form: овал
    barcode_form: OV

Страна:
 Турция:
    annotation_country: Турецкий
 Россия:
    annotation_country: Российский
 Бельгия:
    annotation_country: Бельгийские