collections:
  - armina_972
  - quantum_1086
  - ibiza_1032
  - serenity_1076
  - panama_1391
  - valencia_deluxe_82
  - atlas_1334
  - gavana_1329
  - sierra_1020
  - boston_1130
  - sigma_1093
  - london_1327
  - morocco_1096
  - shaggy_ultra_45
  - platinum_40
  - rio_1052
  - aravia_1133
  - genova_64
  - euphoria_1128
  - matrix_65
  - mayumi_1131
  - colizey_1331
  - mega_carving_42
  - vegas_1308
  - atlantis_1414
  - futura_1087
  - naturel_1419
  - miranda_1426
  - alanya_1427
  - joli_1430
  - perla_1429
  - lissabon_1434
  - richi_1450
  - silver_114
  - tornado_1457
  - graff_1405
  - montana_1550
  - atrium_1445
  - belize_1333
  - elexsus-olimpos_1376
  - lotus_1579
  - hadi_1580
  - aramis_1581
  - moon_1570
  - asadu_1578
  - olimpus_1112
  - alfani_1563
  - safir_951
  - samira_1559
  - sofit_968
  - sofia_1574
  - kabul_1728
  - miledy_1729
  - antep_1640
  - juno_1617
  - cuba_1632
  - ombre_1732
  - iris_1758