collection:
  simone_1337:
    very_small: 3
    small: 2
  tesla_1336:
    very_small: 3
    small: 2
  milena_1115:
    very_small: 3
    small: 2
  magic_1338:
    very_small: 3
    small: 2
  etro_1118:
    very_small: 3
    small: 2
  gavana_1329:
    very_small: 7
    small: 2
  sierra_1020:
    very_small: 7
    small: 2
  colizey_1331:
    very_small: 7
    small: 2
  atlantis_1414:
    very_small: 7
  boston_1130:
    very_small: 7
  crystal_212:
    very_small: 7
  delmar_1377:
    very_small: 7
  futura_1087:
    very_small: 7
  ibiza_1032:
    very_small: 7
  london_1327:
    very_small: 7
  mega_carving_42:
    very_small: 7
  miranda_1426:
    very_small: 7
  naturel_1419:
    very_small: 7
  platinum_40:
    very_small: 7
  richmond_1349:
    very_small: 7
  rio_1052:
    very_small: 7
  shaggy_ultra_45:
    very_small: 7
  sigma_1093:
    very_small: 7
  valencia_deluxe_82:
    very_small: 7
  vegas_1308:
    very_small: 11
    small: 3
