collections:
  - armina_972
  - quantum_1086
  - opera_1122
  - mardan_1120
  - tesla_1336
  - grand_1319
  - ibiza_1032
  - babil_1382
  - baltimore_1332
  - matrix_869
  - serenity_1076
  - crystal_212
  - etro_1118
  - omega_1121
  - panama_1391
  - vera_1386
  - valencia_deluxe_82
  - biblos_1104
  - atlas_1334
  - gavana_1329
  - sierra_1020
  - boston_1130
  - sigma_1093
  - london_1327
  - morocco_1096
  - shaggy_ultra_45
  - platinum_40
  - rio_1052
  - aravia_1133
  - genova_64
  - euphoria_1128
  - matrix_65
  - mayumi_1131
  - peru_1410
  - tempo_1408
  - valentino_1411
  - colizey_1331
  - magic_1338
  - simone_1337
  - uvita_1373
  - mega_carving_42
  - vegas_1308
  - atlantis_1414
  - lali_1421
  - delmar_1377
  - richmond_1349
  - futura_1087
  - eclipse_1424
  - naturel_1419
  - miranda_1426
  - alanya_1427
  - joli_1430
  - perla_1429
  - moda_1105
  - taksim_1433
  - soho_1442
  - star_1246
  - lissabon_1434
  - richi_1450
  - silver_114
  - tornado_1457
  - graff_1405
  - montana_1550
  - atrium_1445
  - belize_1333
  - elexsus-olimpos_1376
  - liman_1571
  - lotus_1579
  - hadi_1580
  - aramis_1581
  - moon_1570
  - asadu_1578
  - olimpus_1112
  - alfani_1563
  - safir_951
  - samira_1559
  - sofit_968
  - sofia_1574
  - alabama_1584
  - sirius_1597
  - nensi_1607
