name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for Linux
        run: |
          docker buildx build --platform linux/amd64 -t your_dockerhub_username/your_image_name:linux-latest .
          docker push your_dockerhub_username/your_image_name:linux-latest

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          sleep 10

      - name: Login to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image for MacOS
        run: |
          docker build -t your_dockerhub_username/your_image_name:macos-latest .
          docker push your_dockerhub_username/your_image_name:macos-latest
